
package dbtest;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AppointmentService", targetNamespace = "http://dbTest/", wsdlLocation = "http://debian:8080/erpisWebServices/AppointmentService?wsdl")
public class AppointmentService
    extends Service
{

    private final static URL APPOINTMENTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(dbtest.AppointmentService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = dbtest.AppointmentService.class.getResource(".");
            url = new URL(baseUrl, "http://debian:8080/erpisWebServices/AppointmentService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://debian:8080/erpisWebServices/AppointmentService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        APPOINTMENTSERVICE_WSDL_LOCATION = url;
    }

    public AppointmentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AppointmentService() {
        super(APPOINTMENTSERVICE_WSDL_LOCATION, new QName("http://dbTest/", "AppointmentService"));
    }

    /**
     * 
     * @return
     *     returns Appointment
     */
    @WebEndpoint(name = "AppointmentPort")
    public Appointment getAppointmentPort() {
        return super.getPort(new QName("http://dbTest/", "AppointmentPort"), Appointment.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Appointment
     */
    @WebEndpoint(name = "AppointmentPort")
    public Appointment getAppointmentPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dbTest/", "AppointmentPort"), Appointment.class, features);
    }

}
