
package dbtest;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CitizenService", targetNamespace = "http://dbTest/", wsdlLocation = "http://debian:8080/erpisWebServices/CitizenService?wsdl")
public class CitizenService
    extends Service
{

    private final static URL CITIZENSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(dbtest.CitizenService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = dbtest.CitizenService.class.getResource(".");
            url = new URL(baseUrl, "http://debian:8080/erpisWebServices/CitizenService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://debian:8080/erpisWebServices/CitizenService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CITIZENSERVICE_WSDL_LOCATION = url;
    }

    public CitizenService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CitizenService() {
        super(CITIZENSERVICE_WSDL_LOCATION, new QName("http://dbTest/", "CitizenService"));
    }

    /**
     * 
     * @return
     *     returns Citizen
     */
    @WebEndpoint(name = "CitizenPort")
    public Citizen getCitizenPort() {
        return super.getPort(new QName("http://dbTest/", "CitizenPort"), Citizen.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Citizen
     */
    @WebEndpoint(name = "CitizenPort")
    public Citizen getCitizenPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dbTest/", "CitizenPort"), Citizen.class, features);
    }

}
