
package dbtest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "InformationMeeting", targetNamespace = "http://dbTest/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InformationMeeting {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDescription", targetNamespace = "http://dbTest/", className = "dbtest.GetDescription")
    @ResponseWrapper(localName = "getDescriptionResponse", targetNamespace = "http://dbTest/", className = "dbtest.GetDescriptionResponse")
    public String getDescription();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setDescription", targetNamespace = "http://dbTest/", className = "dbtest.SetDescription")
    @ResponseWrapper(localName = "setDescriptionResponse", targetNamespace = "http://dbTest/", className = "dbtest.SetDescriptionResponse")
    public void setDescription(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setPlace", targetNamespace = "http://dbTest/", className = "dbtest.SetPlace")
    @ResponseWrapper(localName = "setPlaceResponse", targetNamespace = "http://dbTest/", className = "dbtest.SetPlaceResponse")
    public void setPlace(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setId", targetNamespace = "http://dbTest/", className = "dbtest.SetId")
    @ResponseWrapper(localName = "setIdResponse", targetNamespace = "http://dbTest/", className = "dbtest.SetIdResponse")
    public void setId(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPlace", targetNamespace = "http://dbTest/", className = "dbtest.GetPlace")
    @ResponseWrapper(localName = "getPlaceResponse", targetNamespace = "http://dbTest/", className = "dbtest.GetPlaceResponse")
    public String getPlace();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setDate", targetNamespace = "http://dbTest/", className = "dbtest.SetDate")
    @ResponseWrapper(localName = "setDateResponse", targetNamespace = "http://dbTest/", className = "dbtest.SetDateResponse")
    public void setDate(
        @WebParam(name = "arg0", targetNamespace = "")
        Timestamp arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getName", targetNamespace = "http://dbTest/", className = "dbtest.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://dbTest/", className = "dbtest.GetNameResponse")
    public String getName();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getId", targetNamespace = "http://dbTest/", className = "dbtest.GetId")
    @ResponseWrapper(localName = "getIdResponse", targetNamespace = "http://dbTest/", className = "dbtest.GetIdResponse")
    public int getId();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setName", targetNamespace = "http://dbTest/", className = "dbtest.SetName")
    @ResponseWrapper(localName = "setNameResponse", targetNamespace = "http://dbTest/", className = "dbtest.SetNameResponse")
    public void setName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns dbtest.Timestamp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDate", targetNamespace = "http://dbTest/", className = "dbtest.GetDate")
    @ResponseWrapper(localName = "getDateResponse", targetNamespace = "http://dbTest/", className = "dbtest.GetDateResponse")
    public Timestamp getDate();

}
