
package dbtest;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ManagerService", targetNamespace = "http://dbTest/", wsdlLocation = "http://debian:8080/erpisWebServices/ManagerService?wsdl")
public class ManagerService
    extends Service
{

    private final static URL MANAGERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(dbtest.ManagerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = dbtest.ManagerService.class.getResource(".");
            url = new URL(baseUrl, "http://debian:8080/erpisWebServices/ManagerService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://debian:8080/erpisWebServices/ManagerService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MANAGERSERVICE_WSDL_LOCATION = url;
    }

    public ManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManagerService() {
        super(MANAGERSERVICE_WSDL_LOCATION, new QName("http://dbTest/", "ManagerService"));
    }

    /**
     * 
     * @return
     *     returns Manager
     */
    @WebEndpoint(name = "ManagerPort")
    public Manager getManagerPort() {
        return super.getPort(new QName("http://dbTest/", "ManagerPort"), Manager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Manager
     */
    @WebEndpoint(name = "ManagerPort")
    public Manager getManagerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dbTest/", "ManagerPort"), Manager.class, features);
    }

}
