
package dbtest;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "UserService", targetNamespace = "http://dbTest/", wsdlLocation = "http://debian:8080/erpisWebServices/UserService?wsdl")
public class UserService
    extends Service
{

    private final static URL USERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(dbtest.UserService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = dbtest.UserService.class.getResource(".");
            url = new URL(baseUrl, "http://debian:8080/erpisWebServices/UserService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://debian:8080/erpisWebServices/UserService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        USERSERVICE_WSDL_LOCATION = url;
    }

    public UserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserService() {
        super(USERSERVICE_WSDL_LOCATION, new QName("http://dbTest/", "UserService"));
    }

    /**
     * 
     * @return
     *     returns User
     */
    @WebEndpoint(name = "UserPort")
    public User getUserPort() {
        return super.getPort(new QName("http://dbTest/", "UserPort"), User.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns User
     */
    @WebEndpoint(name = "UserPort")
    public User getUserPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dbTest/", "UserPort"), User.class, features);
    }

}
